//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlePage: Entity
    {
        public string PageContent { get; set; }
        public Nullable<int> ParentArticle { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
