//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article : Entity
    {
        public Article()
        {
            this.ArticlePages = new HashSet<ArticlePage>();
        }
    
        public string Title { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<ArticlePage> ArticlePages { get; set; }
    }
}
